version: '3'
services:
  database:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=url-shortener'
      - 'MYSQL_USER=url-shortener'
      - 'MYSQL_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=secret'
      - 'MARIADB_ROOT_HOST=127.0.0.1'
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 48763:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
volumes:
  dbdata:
